export interface PermissionSeed {
  code: string;
  resource: string;
  action: string;
  description: string;
  isProtected?: boolean;
}

export const PERMISSIONS: PermissionSeed[] = [
  { code: "profile.view", resource: "profile", action: "view", description: "View a candidate profile." },
  { code: "profile.update", resource: "profile", action: "update", description: "Update a candidate profile." },
  { code: "resume.view", resource: "resume", action: "view", description: "View resumes." },
  { code: "resume.create", resource: "resume", action: "create", description: "Create resumes." },
  { code: "resume.update", resource: "resume", action: "update", description: "Update resumes." },
  { code: "resume.delete", resource: "resume", action: "delete", description: "Delete or archive resumes." },
  { code: "application.create", resource: "application", action: "create", description: "Create a job application." },
  { code: "application.view", resource: "application", action: "view", description: "View job applications." },
  { code: "application.withdraw", resource: "application", action: "withdraw", description: "Withdraw an application." },
  { code: "application.review", resource: "application", action: "review", description: "Review applications." },
  { code: "application.shortlist", resource: "application", action: "shortlist", description: "Shortlist applications." },
  { code: "application.reject", resource: "application", action: "reject", description: "Reject applications." },
  { code: "application.move_stage", resource: "application", action: "move_stage", description: "Move applications through the recruitment workflow." },
  { code: "candidate_profile.view", resource: "candidate_profile", action: "view", description: "View candidate profile data in an authorized recruitment context." },
  { code: "interview.view", resource: "interview", action: "view", description: "View interviews." },
  { code: "interview.respond", resource: "interview", action: "respond", description: "Respond to an interview invitation." },
  { code: "interview.create", resource: "interview", action: "create", description: "Schedule interviews." },
  { code: "interview.update", resource: "interview", action: "update", description: "Update interview schedules and details." },
  { code: "interview.cancel", resource: "interview", action: "cancel", description: "Cancel interviews." },
  { code: "interview.evaluate", resource: "interview", action: "evaluate", description: "Evaluate assigned interviews." },
  { code: "notification.view", resource: "notification", action: "view", description: "View notifications." },
  { code: "notification.manage", resource: "notification", action: "manage", description: "Manage notification state and preferences." },
  { code: "saved_job.manage", resource: "saved_job", action: "manage", description: "Manage saved jobs." },
  { code: "company.view", resource: "company", action: "view", description: "View company information." },
  { code: "company.update", resource: "company", action: "update", description: "Update company information." },
  { code: "company.verify", resource: "company", action: "verify", description: "Verify companies at system scope." },
  { code: "company.suspend", resource: "company", action: "suspend", description: "Suspend companies at system scope." },
  { code: "company.member.view", resource: "company.member", action: "view", description: "View company members." },
  { code: "company.member.invite", resource: "company.member", action: "invite", description: "Invite company members." },
  { code: "company.member.update", resource: "company.member", action: "update", description: "Update company members." },
  { code: "company.member.remove", resource: "company.member", action: "remove", description: "Remove company members." },
  { code: "company.role.view", resource: "company.role", action: "view", description: "View company roles." },
  { code: "company.role.manage", resource: "company.role", action: "manage", description: "Manage company-scoped roles within delegation limits." },
  { code: "company.audit.view", resource: "company.audit", action: "view", description: "View company-scoped audit events." },
  { code: "company.ownership.transfer", resource: "company.ownership", action: "transfer", description: "Transfer company ownership.", isProtected: true },
  { code: "job.view", resource: "job", action: "view", description: "View jobs in an authorized context." },
  { code: "job.create", resource: "job", action: "create", description: "Create jobs." },
  { code: "job.update", resource: "job", action: "update", description: "Update jobs." },
  { code: "job.publish", resource: "job", action: "publish", description: "Publish jobs." },
  { code: "job.archive", resource: "job", action: "archive", description: "Archive jobs." },
  { code: "job.delete", resource: "job", action: "delete", description: "Delete eligible job drafts." },
  { code: "job.moderate", resource: "job", action: "moderate", description: "Moderate jobs at system scope." },
  { code: "screening_question.view", resource: "screening_question", action: "view", description: "View job screening questions." },
  { code: "screening_question.manage", resource: "screening_question", action: "manage", description: "Manage job screening questions." },
  { code: "user.view", resource: "user", action: "view", description: "View user accounts at system scope." },
  { code: "user.update", resource: "user", action: "update", description: "Update user accounts at system scope." },
  { code: "user.disable", resource: "user", action: "disable", description: "Disable user accounts at system scope.", isProtected: true },
  { code: "role.view", resource: "role", action: "view", description: "View roles." },
  { code: "role.create", resource: "role", action: "create", description: "Create supported roles." },
  { code: "role.update", resource: "role", action: "update", description: "Update supported roles." },
  { code: "role.delete", resource: "role", action: "delete", description: "Deactivate or delete eligible roles." },
  { code: "role.assign", resource: "role", action: "assign", description: "Assign roles within delegation limits.", isProtected: true },
  { code: "permission.view", resource: "permission", action: "view", description: "View the permission registry." },
  { code: "permission.assign", resource: "permission", action: "assign", description: "Assign permissions within delegation limits.", isProtected: true },
  { code: "audit.view", resource: "audit", action: "view", description: "View system audit events.", isProtected: true },
  { code: "system.authorization.manage", resource: "system.authorization", action: "manage", description: "Manage system authorization policy.", isProtected: true },
  { code: "super_admin.assign", resource: "super_admin", action: "assign", description: "Assign or revoke protected Super Admin authority.", isProtected: true },
];
